spring:
  ###### 配置开启 Spring Boot 对于 bean id 的 override
  main:
    allow-bean-definition-overriding: true
####### 配合连接注册中心 Nacos 信息
  cloud:
    nacos:
      discovery:
        server-addr: http://127.0.0.1:8848
      